language: java
jdk: oraclejdk8
sudo: false
services:
  - mongodb
  - rabbitmq
  - redis-server
env:
  - TERM=dumb SI_FATAL_WHEN_NO_BEANFACTORY=true
script:
  - ./gradlew  :spring-integration-stomp:test -Dtest.single=StompServerIntegrationTests --debug
